spring:
  application:
    name: bookings-microservice
  datasource:
    url: jdbc:h2:mem:testDb
    username: test
    password: test
  flyway:
    enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
com:
  amazonaws:
    xray:
      enabled: false